hadi_set = set()
hadi_set.add(input("num1 :"))
hadi_set.add(input("num2 :"))
hadi_set.add(input("num3 :"))
print(hadi_set)
hadi_list = input("num n :")
hadi_set.update(hadi_list)
print(hadi_list)
print(hadi_set)
print("finish")
print("tayeb allah anfosakom")
